services:
  webapp:
    build: .
    environment:
      - TOKEN_BYTES_LENGTH=8
      - GEOJSON_HOURS_ALIVE=24
    ports:
      - "8000:8000"
    restart: always
  redis:
    image: "redis:alpine"
    restart: always